### ISSUE TITLE
Invoice Not marked as Paid (USD)

### ISSUE THREAD

**Issue by Vsnumimmy** [razorpay/razorpay-whmcs#14] opened 2018-10-31 08:07 UTC
Hello,
My account enabled with international cards but the current whmcs modules does not support USD So the invoice is  not getting updated automatically 

Gateway log 

Unsuccessful-BAD_REQUEST_ERROR:The currency field is required.. Please check razorpay dashboard for Payment id: pay_BGAJJxkDyqeEUM
--
 
So how to resolve this issue ?

**Comment by pulkit8** [comment] 2019-04-04 18:26
Same error. No updates from Razorpay yet.

**Comment by serveradmin247** [comment] 2019-07-30 11:03
This issue still exists.

**Comment by harman28** [comment] 2020-01-08 07:40
Multicurrency support hasn't been added to this plugin yet. Will be done by March 2020.

**Comment by harman28** [comment] 2020-01-08 07:41
Closing as duplicate of #13

**Closed by harman28** 2020-01-08 07:41 UTC
